name: biomarker_mvp
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - app-model==0.4.0
      - appdirs==1.4.4
      - asciitree==0.3.3
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - bermuda==0.1.6
      - build==1.4.0
      - cachey==0.2.1
      - cellpose==4.0.8
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - dask==2025.12.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fasteners==0.20
      - fastremap==1.17.7
      - filelock==3.20.3
      - fill-voids==2.1.1
      - flexcache==0.3
      - flexparser==0.4
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - idna==3.11
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.1
      - in-n-out==0.2.1
      - ipykernel==6.31.0
      - ipython==8.38.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.46.0
      - locket==1.0.0
      - magicgui==0.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - napari==0.6.6
      - napari-console==0.1.4
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.9
      - napari-svg==0.2.1
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - npe2==0.7.9
      - numba==0.63.1
      - numcodecs==0.13.1
      - numpy==2.2.6
      - numpydoc==1.10.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - partd==1.4.2
      - pillow==12.1.0
      - pint==0.24.4
      - platformdirs==4.5.1
      - pooch==1.8.2
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.1
      - psygnal==0.15.1
      - pure-eval==0.2.3
      - pyconify==0.2.1
      - pydantic==2.12.5
      - pydantic-compat==0.1.2
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.2
      - pyside6==6.10.1
      - pyside6-addons==6.10.1
      - pyside6-essentials==6.10.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - roifile==2025.12.12
      - rpds-py==0.30.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - segment-anything==1.0
      - shellingham==1.5.4
      - shiboken6==6.10.1
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - superqt==0.7.7
      - sympy==1.14.0
      - tifffile==2025.5.10
      - tomli==2.4.0
      - tomli-w==1.2.0
      - toolz==1.1.0
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triangle==20250106
      - typer==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - vispy==0.15.2
      - wcwidth==0.2.14
      - wrapt==2.0.1
      - yarl==1.22.0
      - zarr==2.18.3
      - zipp==3.23.0
prefix: C:\Users\claud\miniconda3\envs\biomarker_mvp
